/**
 * Postbuild fallback: garante que public/sw.js existe após next build.
 *
 * O @serwist/next webpack plugin gera o sw.js durante o build.
 * Se ele falhar (ex: Turbopack, erro silencioso), este script
 * compila src/sw.ts com esbuild como fallback.
 *
 * Executa: node scripts/build-sw.mjs
 */

import * as esbuild from "esbuild";
import path from "node:path";
import { fileURLToPath } from "node:url";
import fs from "node:fs";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const projectRoot = path.resolve(__dirname, "..");
const swSrc = path.join(projectRoot, "src", "sw.ts");
const swDest = path.join(projectRoot, "public", "sw.js");

// Se o webpack plugin do Serwist já gerou o sw.js, não faz nada
if (fs.existsSync(swDest)) {
  console.log("✅ sw.js already generated by Serwist webpack plugin — skipping fallback.");
  process.exit(0);
}

console.log("⚠️  sw.js not found — running esbuild fallback...");

const result = await esbuild.build({
  entryPoints: [swSrc],
  outfile: swDest,
  bundle: true,
  platform: "browser",
  target: ["chrome90", "firefox90", "safari14"],
  format: "iife",
  minify: false, // Não minificar: mantém self.__SW_MANIFEST como literal para injeção futura
  sourcemap: false,
  define: {
    // Sem manifest injection neste fallback — precache desativado,
    // mas runtime caching (NetworkFirst/CacheFirst) e offline fallback funcionam
    "self.__SW_MANIFEST": "undefined",
  },
});

if (result.errors.length > 0) {
  console.error("❌ Service worker build failed:");
  for (const error of result.errors) {
    console.error(" ", error.text);
  }
  process.exit(1);
}

const sizeKB = (fs.statSync(swDest).size / 1024).toFixed(1);
console.log(`✅ Service worker built via fallback: public/sw.js (${sizeKB} KB)`);
console.log("   Precaching disabled. Runtime caching and offline fallback active.");
